### ISSUE TITLE
Condition of Merge Join is not displayed

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#121]
spanner-cli can't display conditions of Merge Join.

example query (modified from https://cloud.google.com/spanner/docs/query-execution-operators?hl=en#merge-join)
```
EXPLAIN
SELECT a.AlbumTitle, s.SongName
FROM Albums AS a JOIN@{join_method=merge_join} Songs AS s
ON a.SingerId = s.SingerId AND a.AlbumId = s.AlbumId
AND a.AlbumTitle <> s.SongName;
```

```
$ spanner-cli -p ${CLOUDSDK_CORE_PROJECT} -i ${CLOUDSDK_SPANNER_INSTANCE} -d ${DATABASE_ID} -f test-case.sql -t                           
+----+---------------------------------------------------------------------------------+
| ID | Query_Execution_Plan (EXPERIMENTAL)                                             |
+----+---------------------------------------------------------------------------------+
|  0 | Distributed Union                                                               |
|  1 | +- Serialize Result                                                             |
|  2 |    +- Merge Join                                                                |
|  3 |       +- Local Distributed Union                                                |
|  4 |       |  +- Table Scan (Full scan: true, Table: Albums)                         |
|  8 |       +- Local Distributed Union                                                |
|  9 |          +- Index Scan (Full scan: true, Index: SongsBySingerAlbumSongNameDesc) |
+----+---------------------------------------------------------------------------------+
```

Actually, raw `planNodes` of Merge Join have conditions in `childLinks[2]`(merge join condition) and `childLinks[3]`(residual condition) without the child type.
```
            - childLinks:
                - childIndex: 3
                - childIndex: 8
                - childIndex: 13
                - childIndex: 20
              displayName: Merge Join
              index: 2
              kind: RELATIONAL
...
            - childLinks:
                - childIndex: 14
                - childIndex: 17
              displayName: Function
              index: 13
              kind: SCALAR
              shortRepresentation:
                description: (($SingerId = $SingerId_1) AND ($AlbumId = $AlbumId_1))
...
            - childLinks:
                - childIndex: 21
                - childIndex: 22
              displayName: Function
              index: 20
              kind: SCALAR
              shortRepresentation:
                description: ($AlbumTitle != $SongName)
```

So it can be displayed like

```
$ go run ./ -p ${CLOUDSDK_CORE_PROJECT} -i ${CLOUDSDK_SPANNER_INSTANCE} -d ${DATABASE_ID} -f test-case.sql -t
+----+---------------------------------------------------------------------------------+
| ID | Query_Execution_Plan (EXPERIMENTAL)                                             |
+----+---------------------------------------------------------------------------------+
|  0 | Distributed Union                                                               |
|  1 | +- Serialize Result                                                             |
| *2 |    +- Merge Join                                                                |
|  3 |       +- Local Distributed Union                                                |
|  4 |       |  +- Table Scan (Full scan: true, Table: Albums)                         |
|  8 |       +- Local Distributed Union                                                |
|  9 |          +- Index Scan (Full scan: true, Index: SongsBySingerAlbumSongNameDesc) |
+----+---------------------------------------------------------------------------------+
Predicates(identified by ID):
 2: Condition: (($SingerId = $SingerId_1) AND ($AlbumId = $AlbumId_1))
    Residual Condition: ($AlbumTitle != $SongName)
```

Note:
The official plan visualizerIt also can't display it but it should be displayed.
![official visualizer](https://user-images.githubusercontent.com/803393/139827427-977afdd3-b506-4ce7-b0dc-3678272931d5.png)

It needs to investigate `LEFT [OUTER] JOIN`, `RIGHT [OUTER] JOIN`, `FULL [OUTER] JOIN`.
