### ISSUE TITLE
EXPLAIN with subqueries shows duplicated subtrees

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#89]
Some plan with subqueries show duplicate subtrees.

https://cloud.google.com/spanner/docs/query-execution-operators?hl=en#array_subqueries
```sql
SELECT a.AlbumId,
ARRAY(SELECT ConcertDate
      FROM Concerts
      WHERE Concerts.SingerId = a.SingerId)
FROM Albums AS a;
```
```
+-----+------------------------------------------------------------------+
| ID  | Query_Execution_Plan (EXPERIMENTAL)                              |
+-----+------------------------------------------------------------------+
|   0 | Distributed Union                                                |
|   1 | +- Local Distributed Union                                       |
|   2 |    +- Serialize Result                                           |
|   3 |       +- Index Scan (Full scan: true, Index: AlbumsByAlbumTitle) |
|   7 |       +- Array Subquery                                          |
|  *8 |       |  +- Distributed Union                                    |
|   9 |       |     +- Local Distributed Union                           |
| *10 |       |        +- FilterScan                                     |
|  11 |       |           +- Index Scan (Index: ConcertsBySingerId)      |
|   7 |       +- [Scalar] Array Subquery                                 |
|  *8 |          +- Distributed Union                                    |
|   9 |             +- Local Distributed Union                           |
| *10 |                +- FilterScan                                     |
|  11 |                   +- Index Scan (Index: ConcertsBySingerId)      |
+-----+------------------------------------------------------------------+
Predicates(identified by ID):
  8: Split Range: ($SingerId_1 = $SingerId)
 10: Seek Condition: ($SingerId_1 = $SingerId)
  8: Split Range: ($SingerId_1 = $SingerId)
 10: Seek Condition: ($SingerId_1 = $SingerId)
```

This happens because the actual query plan have duplicate children.

```yaml
    - childLinks:
      - childIndex: 3 -- link to Index Scan
      - childIndex: 6 -- link to Reference: $AlbumId
      - childIndex: 7 -- link to Array Subquery
      - childIndex: 7 -- link to Array Subquery(same as above)
        type: Scalar
      displayName: Serialize Result
      index: 2
      kind: RELATIONAL
```

Note:

Another scalar subquery only have a link with `type: Scalar`.
https://cloud.google.com/spanner/docs/query-execution-operators?hl=en#scalar_subqueries

```sql
SELECT FirstName,
IF(FirstName='Alice',
   (SELECT COUNT(*)
    FROM Songs
    WHERE Duration > 300),
   0)
FROM Singers;
```
```
+-----+-----------------------------------------------------------------------+
| ID  | Query_Execution_Plan (EXPERIMENTAL)                                   |
+-----+-----------------------------------------------------------------------+
|   0 | Distributed Union                                                     |
|   1 | +- Local Distributed Union                                            |
|   2 |    +- Serialize Result                                                |
|   3 |       +- Index Scan (Full scan: true, Index: SingersByFirstLastName)  |
|  10 |       +- [Scalar] Scalar Subquery                                     |
|  11 |          +- Global Stream Aggregate (scalar_aggregate: true)          |
|  12 |             +- Distributed Union                                      |
|  13 |                +- Local Stream Aggregate (scalar_aggregate: true)     |
|  14 |                   +- Local Distributed Union                          |
| *15 |                      +- FilterScan                                    |
|  16 |                         +- Table Scan (Full scan: true, Table: Songs) |
+-----+-----------------------------------------------------------------------+
Predicates(identified by ID):
 15: Residual Condition: ($Duration > 300)
```
```yaml
    - childLinks:
      - childIndex: 3  -- link to Index Scan
      - childIndex: 5  -- link to Reference: $FirstName
      - childIndex: 6  -- link to Function: IF(($FirstName = 'Alice'), $sv_1, 0)
      - childIndex: 10 -- link to Scalar Subquery
        type: Scalar
      displayName: Serialize Result
      index: 2
      kind: RELATIONAL
```

Implementation choices:
* When child link with same node ID is appeared in same parent node, 
ignore everything except the first one(or the last one?)
* In Serialize Result, the first child and children with `type: Scalar` seems appropriate subtree.
